import { Metadata } from 'next';
import { SITE_NAME, SITE_URL } from '../lib/metadata';

export const metadata: Metadata = {
  title: `Dịch vụ số uy tín tại Nha Trang - Giá tốt nhất | ${SITE_NAME}`,
  description: 'Cung cấp tài khoản và dịch vụ số chính hãng: YouTube Premium, Google Drive, Netflix, TikTok, Facebook, Instagram, AI ChatGPT với giá tốt nhất tại Nha Trang. Giao tự động 24/7, bảo hành dài hạn.',
  keywords: [
    'dịch vụ số Nha Trang',
    'tài khoản YouTube Premium Nha Trang',
    'Google Drive unlimited Nha Trang',
    'Netflix premium Nha Trang',
    'TikTok ads Nha Trang',
    'Facebook business Nha Trang',
    'Instagram premium Nha Trang',
    'ChatGPT Plus Nha Trang',
    'dịch vụ AI Nha Trang',
    'tài khoản số giá rẻ Nha Trang',
    'Spotify premium Nha Trang',
    'Canva Pro Nha Trang',
    'Adobe Creative Nha Trang',
    'Office 365 Nha Trang',
    'dịch vụ marketing Nha Trang',
    'thiết kế đồ họa Nha Trang',
    'tài khoản chính hãng Nha Trang',
    'giao hàng tự động Nha Trang',
    'bảo hành tài khoản Nha Trang',
    'mua tài khoản uy tín Nha Trang',
  ],
  openGraph: {
    title: `Dịch vụ số uy tín Nha Trang - YouTube, Google, Netflix, AI | ${SITE_NAME}`,
    description: 'Mua tài khoản số chính hãng tại Nha Trang: YouTube Premium, Google Drive, Netflix, ChatGPT Plus với giá tốt nhất. Giao tự động 24/7, bảo hành dài hạn.',
    url: `${SITE_URL}/services`,
    type: 'website',
    siteName: SITE_NAME,
    locale: 'vi_VN',
    images: [
      {
        url: `${SITE_URL}/images/services/gemini.jpg`,
        width: 1200,
        height: 630,
        alt: 'Dịch vụ số uy tín tại Nha Trang - YouTube Premium, Google Drive, Netflix',
        type: 'image/jpeg',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    site: '@nhatranginsight',
    creator: '@nhatranginsight',
    title: `Dịch vụ số uy tín Nha Trang - Giá tốt nhất 2025`,
    description: 'Tài khoản số chính hãng: YouTube Premium, Google Drive, Netflix, ChatGPT Plus. Giao tự động 24/7, bảo hành dài hạn.',
    images: [{
      url: `${SITE_URL}/images/services/gemini.jpg`,
      alt: 'Dịch vụ số uy tín tại Nha Trang',
    }],
  },
  alternates: {
    canonical: `${SITE_URL}/services`,
    languages: {
      'vi-VN': `${SITE_URL}/services`,
      'en-US': `${SITE_URL}/services?lang=en`,
      'ko-KR': `${SITE_URL}/services?lang=kr`,
      'zh-CN': `${SITE_URL}/services?lang=zh-CN`,
      'zh-TW': `${SITE_URL}/services?lang=zh-TW`,
      'ru-RU': `${SITE_URL}/services?lang=ru`,
    },
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  category: 'Digital Services',
  classification: 'E-commerce Services',
  other: {
    'geo.region': 'VN-56',
    'geo.placename': 'Nha Trang, Khánh Hòa',
    'geo.position': '12.2388;109.1967',
    'ICBM': '12.2388, 109.1967',
    'DC.title': 'Dịch vụ số uy tín tại Nha Trang',
    'DC.subject': 'Dịch vụ số, Tài khoản premium, E-commerce, Nha Trang',
    'DC.description': 'Cung cấp tài khoản và dịch vụ số chính hãng với giá tốt nhất tại Nha Trang',
    'DC.creator': SITE_NAME,
    'DC.language': 'vi-VN',
    'DC.coverage': 'Nha Trang, Khánh Hòa, Việt Nam',
    'product.price.currency': 'VND',
    'product.availability': 'InStock',
    'business.contactdata.street_address': '2/18 Ngô Đến, Vĩnh Phước',
    'business.contactdata.locality': 'Nha Trang',
    'business.contactdata.region': 'Khánh Hòa',
    'business.contactdata.postal_code': '650000',
    'business.contactdata.country_name': 'Vietnam',
  },
}; 